export type { IAgent, AgentProposal, AgentVote, AgentIdentity } from "./IAgent"
export type { ICoordinator, ConsensusResult, CycleReport } from "./ICoordinator"
export type { IExecutor, ExecutionResult } from "./IExecutor"
export type { IReputation, AgentStats } from "./IReputation"
export type { ISafetyGuard, SafetyStatus } from "./ISafetyGuard"
export type { IResourceManager, ResourceRequest, ResourceGrant, ResourceState } from "./IResourceManager"
export type { IAudit, AuditEntry, AuditReport } from "./IAudit"
export type { ICompliance, ComplianceCheck, CompliancePolicy } from "./ICompliance"
export type { ILearningEngine, LearningFeedback, AgentParams } from "./ILearningEngine"

export { ResourceManager } from "./resource-manager"
export { SafetyGuard, type SafetyGuardConfig } from "./safety-guard"
export { Audit } from "./audit"
export { Reputation } from "./reputation"
export { Compliance } from "./compliance"
export { LearningEngine } from "./learning-engine"
export { OracleConditions } from "./oracle-conditions"
export { Voting, type VoteRecord, type VoteResult } from "./voting"
export { Coordinator, type CoordinatorConfig } from "./coordinator"
export type { SubmissionResult } from "./ICoordinator"
export { TradingAdapter } from "./trading-adapter"
export type { TradeSignal } from "./trading-adapter"
export type { AgentIntent, IntentRecord, IntentStatus, IntentFilter, IIntentPublisher } from "./intent-types"
export { IntentPublisher } from "./intent-publisher"
export { IntentDeduplicator } from "./intent-deduplicator"
export type { KnowledgeRequest, KnowledgeReport } from "./knowledge-types"
export { KnowledgeService } from "./knowledge-service"
export { frameworkReputation, frameworkAudit, frameworkIntents, frameworkKnowledge, frameworkCoordinator } from "./singletons"
